name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Login ke GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop dan Hapus Kontainer Lama
        shell: powershell
        run: |
          docker stop my-web
          docker rm my-web
        continue-on-error: true

      - name: Pull Image Terbaru dari GHCR
        shell: powershell
        run: |
          docker pull ghcr.io/mack3nzie-ai/devops-app:latest

      - name: Jalankan Kontainer Baru
        shell: powershell
        run: |
          docker run -d -p 8080:3000 --name my-web ghcr.io/mack3nzie-ai/devops-app:latest